# ::: -------------------------------------------------------------------- ::: #
# ::: >>> SECTION | MAIN CONFIGURATION <<<                                 ::: #
# ::: -------------------------------------------------------------------- ::: #
parameters:
  - default

config:
  general:
    name:
      model: {{ cookiecutter.project_slug }}
      scenario: Basic
  # -------------------------------------------------------------------------- #
  optimization:
    problem_type: LP
    snapshots:
      count: 24
    solver:
      name: highs
  # -------------------------------------------------------------------------- #
  results:
    enabled: true
  # -------------------------------------------------------------------------- #
  files:
    data: example.csv
  # -------------------------------------------------------------------------- #
  paths:
    files: data/timeseries/
    components: data/components/
    parameters: data/parameters/
    templates: templates/
    results: out/

# ::: -------------------------------------------------------------------- ::: #
# ::: >>> SECTION | ENERGY CARRIERS <<<                                    ::: #
# ::: -------------------------------------------------------------------- ::: #
carriers:
  electricity: {}

# ::: -------------------------------------------------------------------- ::: #
# ::: >>> SECTION | MODEL COMPONENTS <<<                                   ::: #
# ::: -------------------------------------------------------------------- ::: #
# Uncomment the following lines to load components from CSV files:
# load_components:
#   - some_specific_model_file.csv

components:
  grid:
    type: Node
    carrier: electricity
  
  market:
    type: Profile
    carrier: electricity
    node_to: grid
    mode: create
    cost: 100.0
  
  demand:
    type: Profile
    carrier: electricity
    node_from: grid
    value: 07_demand1_value@data
